Milestone 2 Initilize Redux
FrancoRosa/react-bookstore pull request #2
Opened 2020-10-21 22:21 UTC by FrancoRosa

Hello TSE
In this milestone I manage to:

- Prepare the directory structure
- Create the book reducer
- Implement the App component
- Implement the BooksList component
- Implement the Book component
- Implement the BooksForm component
- Define the Redux actions and reducers
- Initialize the Redux store

Please give me some feedback.

2020-10-21 22:52 UTC, bellom requested changes
## Hi @FrancoRosa  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Changes Required! ♻️ 

**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-10-21 22:52 UTC, bellom commented on src/components/BooksForm.js
> +import React from 'react';
Let's do some rearrangement (create `container` folder and put `BookForm.js` in it)
React bindings for Redux separate presentational components from container components. This approach can make your app easier to understand and allow you to more easily reuse components. In your components directory (presentational components) you have components that are not connected to the Redux store, and on your containers directory, you have components that are connected to the Redux store. https://redux.js.org/basics/usage-with-react#presentational-and-container-components 

![image](https://user-images.githubusercontent.com/31897434/90568251-6ba33b80-e1a3-11ea-990d-e73db732b31b.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896827/

2020-10-21 22:52 UTC, bellom commented on src/components/BooksList.js
> +import React from 'react';
Let's do some rearrangement (create `container` folder and put `BookList.js` in it)
React bindings for Redux separate presentational components from container components. This approach can make your app easier to understand and allow you to more easily reuse components. In your components directory (presentational components) you have components that are not connected to the Redux store, and on your containers directory, you have components that are connected to the Redux store. https://redux.js.org/basics/usage-with-react#presentational-and-container-components 

![image](https://user-images.githubusercontent.com/31897434/90568251-6ba33b80-e1a3-11ea-990d-e73db732b31b.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896827/

2020-10-21 22:52 UTC, bellom commented on src/components/BooksList.js
> +  books: PropTypes.arrayOf(Book.propTypes).isRequired,
Using [PropTypes.shape](https://dev.to/cesareferrari/how-to-specify-the-shape-of-an-object-with-proptypes-3c56) here will allow you to set a type check that is more accurate.

2020-10-21 22:52 UTC, bellom commented on src/reducers/index.js
> +];
`initialState` shoud be inside `src/index.js`
![image](https://user-images.githubusercontent.com/31897434/96794293-d831f500-13f5-11eb-8de7-312f5faf81f3.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896827/

2020-10-21 22:52 UTC, bellom commented on src/reducers/books.js
> +];
`initialState` shoud be inside `src/index.js`
![image](https://user-images.githubusercontent.com/31897434/96794293-d831f500-13f5-11eb-8de7-312f5faf81f3.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896827/

2020-10-22 04:15 UTC, FrancoRosa commented
Thank you @bellom for your kind review and suggestions
I did the required changes

2020-10-22 05:59 UTC, wathigo approved these changes
### Approved :heavy_check_mark: 
Great job implementing the suggested changes.

**You may proceed to the next milestone.**

**Happy Hacking :man_technologist: 
Simon Wathigo.**

2020-10-22 21:43 UTC, merged