Milestone 3 Actions
FrancoRosa/react-bookstore pull request #3
Opened 2020-10-22 21:41 UTC by FrancoRosa

Hello TSEs,
In this milestone I did the following tasks:

- Implement the handlers for input and select on BooksForm.
- Implement a submit handler to save the book on Redux store
- Add a new column to the BooksList component with the remove button.
- Pass the remove handler as props and use and action to remove the book from redux.

Thank you for your kind review and feedback

2020-10-22 22:23 UTC, bellom requested changes
## Hi @FrancoRosa  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Changes Required! ♻️ 

**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-10-22 22:31 UTC, bellom requested changes

2020-10-22 22:31 UTC, bellom commented on src/containers/BooksForm.js
> +  }
According to the instruction on pathwright;

we need to make use of `handleChange` method to handle both `input changes` and `select category`.

![image](https://user-images.githubusercontent.com/31897434/96936548-332f1f00-14be-11eb-875c-a33587ae4de0.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896828/

i.e we could have it this wat;

```
handleChange(event) {
  const name = event.target.name;

  this.setState({
    title: event.target.value
    [name]: event.target.value
  })
}
```

**OR**

```
handleChange(event) {
  this.setState({
    input: event.target.value
    select: event.target.value
  })
}
```

2020-10-23 13:45 UTC, FrancoRosa commented
Thank you @bellom for your feedback
The requested improvements were made.

2020-10-23 15:20 UTC, Torres-ssf approved these changes
### Milestone Approved :+1: :hand: 
Hi @FrancoRosa :hand: 
Great job on this milestone and implementing the requested changes.
You may merge the PR.

Happy Coding :computer: 
**Sergio Torres**

2020-10-23 22:46 UTC, merged